In [1]:
import torch

In [4]:
torch.manual_seed(111)
t1 = torch.randint(low=0, high=10,size=(5,5))
print(t1)

tensor([[0, 2, 6, 8, 2],
        [7, 1, 6, 4, 4],
        [4, 9, 3, 3, 4],
        [8, 9, 6, 6, 0],
        [6, 6, 9, 6, 6]])


### 返回（0,1）（1,2）

In [5]:
print(t1[[0, 1],[1, 2]])

tensor([2, 6])


### 返回（1, 2）（2， 4）

In [6]:
print(t1[[1, 3],[2, 4]])

tensor([6, 0])


### 取0,1行的第1,2列四个元素

In [15]:
print(t1[:2,1:3])

tensor([[2, 6],
        [1, 6]])


### 所有奇数行， 偶数行

In [18]:
print(t1[::2, :])
print(t1[1::2, :])

tensor([[0, 2, 6, 8, 2],
        [4, 9, 3, 3, 4],
        [6, 6, 9, 6, 6]])
tensor([[8, 9, 6, 6, 0]])


### 所有奇数行， 偶数列

In [20]:
print(t1[::2, 1::2])

tensor([[2, 8],
        [9, 3],
        [6, 6]])


### bool 类型

In [21]:
print(t1[torch.tensor([True, False, True, False, True]), :])

tensor([[0, 2, 6, 8, 2],
        [4, 9, 3, 3, 4],
        [6, 6, 9, 6, 6]])


In [32]:
# 第三列所有大于五的数字
print(t1[:,t1[: ,2] > 5])

tensor([[0, 2, 8, 2],
        [7, 1, 4, 4],
        [4, 9, 3, 4],
        [8, 9, 6, 0],
        [6, 6, 6, 6]])
